// Copyright (c) Lawrence Livermore National Security, LLC and other VisIt
// Project developers.  See the top-level LICENSE file for dates and other
// details.  No copyright assignment is required to contribute to VisIt.

#include <SlugCodePluginInfo.h>

VISIT_DATABASE_PLUGIN_ENTRY(SlugCode,Engine)

// ****************************************************************************
//  Method: SlugCodeEnginePluginInfo::GetWriter
//
//  Purpose:
//      Sets up a SlugCode writer.
//
//  Returns:    A SlugCode writer.
//
//  Programmer: generated by xml2info
//  Creation:   omitted
//
// ****************************************************************************
avtDatabaseWriter *
SlugCodeEnginePluginInfo::GetWriter(void)
{
    return NULL;
}

