HOST = $(shell hostname)

HDF5_DIR =
MPI_DIR  =
# optional
TAU_DIR =

# ylee macbook
ifeq ($(HOST),crate)
	HDF5_DIR = /usr/local
	MPI_DIR  = /usr/local
	TAU_DIR  = /Users/ylee/src/tau-2.28.1/apple
endif
